# Generated by Django 5.2.11 on 2026-02-14 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа')])),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(blank=True, default=None, upload_to='catalog/category/')),
            ],
        ),
    ]
