# Generated by Django 5.2.11 on 2026-02-15 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='catalog/category/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Минимум 3 символа')], verbose_name='Подкатегория')),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(blank=True, default=None, upload_to='catalog/subcategory/', verbose_name='Изображение')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcat', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Податегории',
            },
        ),
    ]
