# Generated by Django 5.2.11 on 2026-02-15 09:25

import apps.catalog.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Товар')),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(blank=True, default=None, upload_to=apps.catalog.utils.product_image_path, verbose_name='Изображение')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
