# Generated by Django 5.2.11 on 2026-02-15 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Товар'),
        ),
    ]
