# Generated by Django 5.2.11 on 2026-02-15 10:52

import apps.catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to=apps.catalog.utils.product_image_path, verbose_name='Изображение'),
        ),
    ]
