# Generated by Django 5.2.11 on 2026-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
