# Generated by Django 5.2.11 on 2026-02-18 09:35

import apps.catalog.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=apps.catalog.utils.product_image_path, verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['-is_main', 'order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product', 'is_main'), name='unique_main_image_per_product')],
            },
        ),
    ]
