# Generated by Django 5.2.11 on 2026-02-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_picture_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
