# Generated by Django 5.2.11 on 2026-02-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_sku_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Артикул'),
        ),
    ]
